<a href="https://colab.research.google.com/github/Anishya181/Deep_Learning_Models/blob/main/DigitRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),

  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),

  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.4938918 , -0.06810912, -0.34807912,  0.3161745 ,  0.60237557,
        -0.20680979,  0.00257099, -0.12455518,  0.90050006, -0.0404276 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.13008447, 0.0741569 , 0.05604826, 0.10890399, 0.14499043,
        0.06455273, 0.07958799, 0.07008697, 0.19534989, 0.07623834]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.740273

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2969 - accuracy: 0.9138
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1439 - accuracy: 0.9571
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1058 - accuracy: 0.9677
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0888 - accuracy: 0.9726
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0757 - accuracy: 0.9761
Epoch 6/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0647 - accuracy: 0.9797
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0588 - accuracy: 0.9811
Epoch 8/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0533 - accuracy: 0.9827
Epoch 9/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0478 - accuracy: 0.9842
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0684 - accuracy: 0.9807 - 630ms/epoch - 2ms/step


[0.06840072572231293, 0.9807000160217285]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.96395027e-11, 1.43525625e-11, 3.34895489e-08, 3.16263640e-06,
        2.68457647e-13, 7.60869856e-09, 7.87622917e-17, 9.99996066e-01,
        3.87575794e-09, 7.45459147e-07],
       [1.54626704e-07, 4.80805320e-04, 9.99518394e-01, 6.51937171e-07,
        3.48328444e-18, 6.73429952e-08, 3.58767904e-10, 1.86235744e-17,
        9.42969880e-09, 6.61658929e-20],
       [3.39339437e-07, 9.99927521e-01, 1.76892154e-05, 8.05296054e-07,
        3.29785107e-05, 3.99961948e-07, 2.13984708e-06, 9.37690402e-06,
        8.71982957e-06, 4.29794582e-08],
       [9.99984384e-01, 2.17002563e-13, 6.36307004e-06, 8.51134629e-09,
        2.35317987e-08, 5.02675199e-08, 6.55203348e-06, 1.22704557e-06,
        9.74056280e-10, 1.48147217e-06],
       [2.98820879e-08, 3.72588835e-11, 6.75269973e-07, 4.14645491e-08,
        9.99610364e-01, 8.36366098e-07, 3.08866106e-07, 1.98542821e-05,
        5.46345369e-08, 3.67969536e-04]], dtype=float32)>

In [ ]:
print(y_test[:5])

[7 2 1 0 4]
